substitutions:
  name: "home-assistant-voice-194365"
  friendly_name: Home Assistant Voice 194365
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
                                    
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: /awSKQvKilwYr8KsNcFjUKb/COvC9TowR6EGKu0M3lA=
network:
    enable_ipv6: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.178.185
    gateway: 192.168.178.1
    subnet: 255.255.255.0

#################################################################################################################
micro_wake_word:
  id: mww 
  models:
    - model: https://raw.githubusercontent.com/amac16/Custom_V2_MicroWakeWords/247ba6d60018adb944d5d797273015fa723945c4/models/computer/computer.json
      id: computer
    - id: alexa
      model: https://raw.githubusercontent.com/esphome/micro-wake-word-models/refs/heads/main/models/v2/alexa.json
#    - id: svenjamin
#      model: https://raw.githubusercontent.com/Mariuss811/WakeWord/main/models/svenjamin/svenjamin.json
    - model: /config/esphome/models/svenjamin/svenjamin1.json
      id: svenjamin
#    - id: !remove hey_mycroft
#    - id: !remove hey_jarvis

logger:
# level: none
# level: error
# level: warn
#  level: info
  level: debug
# level: verbose
#  level: very_verbose